### ISSUE TITLE
patchXMLHTTPRequest always sends "uniqueId" === 1

### ISSUE THREAD

**Issue by sod** [GoogleChromeLabs/tti-polyfill#16]
See https://github.com/GoogleChromeLabs/tti-polyfill/blob/master/src/activityTrackerUtils.js#L27

![image](https://user-images.githubusercontent.com/905328/60279022-aa6f9580-9900-11e9-8750-627d786466d7.png)

The `uniqueId` is raised only once on patch time and not on runtime, thus 

`beforeXHRSendCb(requestId);`
and
`onRequestCompletedCb(requestId)`

is kinda just like
`beforeXHRSendCb(1);`
and
`onRequestCompletedCb(1)`

**Comment by iadolgov** [comment]
> See https://github.com/GoogleChromeLabs/tti-polyfill/blob/master/src/activityTrackerUtils.js#L27
> 
> ![image](https://user-images.githubusercontent.com/905328/60279022-aa6f9580-9900-11e9-8750-627d786466d7.png)
> 
> The `uniqueId` is raised only once on patch time and not on runtime, thus
> 
> `beforeXHRSendCb(requestId);`
> and
> `onRequestCompletedCb(requestId)`
> 
> is kinda just like
> `beforeXHRSendCb(1);`
> and
> `onRequestCompletedCb(1)`

Hi, did you find the fix?

**Comment by sod** [comment]
just saw someone already posted a PR for it https://github.com/GoogleChromeLabs/tti-polyfill/pull/13

**Comment by iadolgov** [comment]
> just saw someone already posted a PR for it #13

yep, me too

**Comment by sod** [comment]
We don't use the polyfill anymore.
